### ISSUE TITLE
geography / device etc. tracking

### ISSUE THREAD

**Issue by dcsan** [botanio/sdk#24]
does any of this work? does yandex have some back connection to telegraph servers to add meta data over the message IDs? I hope not :)

i see all my users coming from germany, even though my app server is in the US. how does that work exactly?

**Comment by ollmer** [comment]
Hello! Appmetrica originally designated as service for mobile apps, not for bots specifically. So, those fields are useless in our case, we don't send any values to them. Because all we have is just data that you've sent to us in track request. Yandex doesn't have any connection with telegram. Germany in geo reports it's just location of our botan server, appmetrica detect it from ip address.
